baseurl: ''
permalink: pretty
title: 'Bystry Lisek'

homepage:
  show_call_box: true
  show_modal: true
  show_modal_until: '2022-03-22'

logo:
  mobile: "images/logo/bystryLisek_bw.svg"
  desktop: "images/logo/bystryLisek_bw.svg"
  desktop_height: "72px"

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Bystry Lisek"
  meta_og_type: "website"
  meta_og_url: "https://www.bystrylisek.pl"
  meta_og_image: "/images/logo/bystryLisek_og.png"
  meta_og_description: "Gabinet psychologiczno-pedagogiczny Bystry Lisek to miejsce, w którym każde dziecko może rozwinąć swoje skrzydła."
  meta_twitter_card: ""
  meta_twitter_site: ""
  meta_twitter_creator: ""

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
